# Generated by Django 5.1.3 on 2024-11-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_user_is_active_user_is_staff_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.CharField(max_length=50),
        ),
    ]
